### ISSUE TITLE
Drop down menu for preferences not loading

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/Strawberry-Fields-2018#10]
Heya @jarvisjohnson could you please look at this error for me?
On the Applications page, under Job Preferneces, if you try to select an option, eg. Wilderness, I get this error message.

I hope this is a quick fix as I'm hoping to send out offers on 31st Aug, Friday afternoon here and need to make sure I select the right amount of Wilderness people etc :)

<img width="747" alt="preferences error" src="https://user-images.githubusercontent.com/29219132/44767484-60fbd000-aba1-11e8-8cb8-7004182ba3c1.PNG">

**Comment by jarvisjohnson** [comment]
ah whoops - all of those filters were broken.  They are fixed now

**Comment by KimPong** [comment]
legend - thanks heaps @jarvisjohnson
