### ISSUE TITLE
Admin access for vol intern

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/Strawberry-Fields-2018#11]
Hey @jarvisjohnson , I'm gunna get my new intern to help me rate the volunteers, so it would be great if you could create an admin account for the vols email address that he can use?

username: volunteers@strawberry-fields.com.au
password: Vod05021

lemme know! xx

**Comment by jarvisjohnson** [comment]
Ok @KimPong this user has been created and can access the admin
