### ISSUE TITLE
volunteer offer email

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/Strawberry-Fields-2018#12]
@jarvisjohnson could you please confirm our offer confirmation email is set up so i can start sending out offers? xx

if it needs text, it can say:

Congratulations on being accepted as a volunteer at Strawberry Fields 2018!
Please log in by following the link below and click 'Confirm My Spot' or 'Decline'.
This must be done by midnight 11 September to secure your spot.

Please refer to the Strawberry Fields[ website](https://www.strawberry-fields.com.au/volunteer-applications/) for full description of the role requirements and FAQs and make sure you read over the [Volunteer Agreement](https://strawberry-fields.shyftly.com/pages/volunteer_terms) before accepting your position.

Much love,
SF

**Comment by KimPong** [comment]
or, shall i just message all accepted applicants through the message centre? are you feeling good about how that is set up?
If so, I'd just need to know the best link/instructions to put in to direct them to log in and go to the their confirmation page.
@jarvisjohnson

**Comment by jarvisjohnson** [comment]
Yes, an email will be sent to each person when you accept them.  I've updated this text - but I can't change the text for each festival, so I've left out the sentence asking to refer to the SF site.  I would like to make the text of these emails customisable in future.  I think for now send that part as a message view the admin if you don't mind.

Yes the messaging feature works - I believe you've already used it to send a bulk message to everyone yeah?

Makes me think - there are a few messages in the admin area that people have sent to you - did you not get email notifications for the messages?

**Comment by KimPong** [comment]
@jarvisjohnson thanks! 
i've just tested the acceptance email again and it's all good - except is it possible to just delete this para? as the terms have changed..
'Please remember that, as stated in the volunteer agreement, if you do not show up to your shift, do not complete your shift or if you pull out within 21 days of the event (without a reasonable excuse such as a medical issue) you will be charged the non attendance fee of $400.'

yep sent a bulk message :) and i belive i've gotten notifications for the other ones, but have been too busy to reply! will reply tho :)
