### ISSUE TITLE
waitlist email text - if required

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/Strawberry-Fields-2018#13]
@jarvisjohnson  can use this if still setting up a 'submit and send' emails.

Hi there,

Thank you very much for taking the time to apply for Strawberry Fields' volunteer program. 
We received twice as many applications as there are positions, so unfortunately at this stage we are unable to offer you a spot.
HOWEVER, it is most likely that we will have more positions to offer over the coming weeks, as people's circumstances change.
We would like to include you on our waiting list, and will be in touch as soon as possible should a position become available.

Please remember that we do not refund previously purchased tickets if a person accepts a volunteer spot, however there is information regarding ticket name changes on the Strawberry Fields website.

Looking forward to seeing you for our 10th anniversary!

Much love,
SF

**Comment by jarvisjohnson** [comment]
Ok have updated text in this email.  Sorry, again I can't be updating it specifically for each festival iteration - I'd like to make the text for each email customisable in the admin at some point.

I believe you just tried accepting and waitlisting a couple of your profiles - those emails you would have got were the old text (and I believe the SF logo wouldn't have shown up).  If you try now you'll get the updated copy.  ( i need to set your test applications to not be accepted / waitlisted first )

**Comment by KimPong** [comment]
oh great thanks - yes the old emails have come through now - no worries re customised response! @jarvisjohnson
