### ISSUE TITLE
error message when attempting to edit shifts

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/Strawberry-Fields-2018#16]
Hey @jarvisjohnson I have been getting this error message when I attempt to edi a shift time, or assign volunteers to a shift.

Just getting this section all ship shape so we can send shifts out in 2 weeks.

xx

<img width="741" alt="edit shift error message" src="https://user-images.githubusercontent.com/29219132/45738462-d81e0480-bc33-11e8-8171-4583aac78d49.PNG">

**Comment by jarvisjohnson** [comment]
Ok will take a look at these issues in the next couple of days

**Comment by KimPong** [comment]
@jarvisjohnson thanks, i'd say this and the one about scheduling in multiple departments are most pertinent at the moment, as we are wanting to send shifts out next Tuesday/Wed xx

**Comment by jarvisjohnson** [comment]
Ok this is fixed now

**Comment by KimPong** [comment]
Thanks :)
