### ISSUE TITLE
details for managing portal/Stripe queries

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/Strawberry-Fields-2018#4]
Hey @jarvisjohnson i've had hundreds and hundreds of email already this year about volunteering at SF, so i feel like when we launch next Tuesday, we will get a shit load of queries about credit cards not being valid etc.

Before next Tues can you provide me with the details for the stripe account, and any other kind of instructions for common issues, so i can try to resolve these issues myself, given how you're super busy with work atm?

on that note, if we can knock over those last few updates, it might be worth getting the page up a day before we officially announce, so that if we find any little bugs when people start applying, we can fix it before the website gets hit!
There are already people finding the password - protected page that Tara made and asking if they have missed out etc
xx

**Comment by jarvisjohnson** [comment]
@KimPong  - You should be getting an email from Stripe asking you to setup the Stripe account for SF.

(to volunteers@strawberry-fields.com.au)

You will need some of their business info - here is their ABN info: https://abr.business.gov.au/ABN/View?abn=50139653348

you'll need to get their bank account details as well.

There will be nothing in the Stripe Dashboard at the minute, but that is the dashboard where you could charge people for missed shifts, see why their credit cards haven't gone through. Its very easy to navigate, but as there is no data in there yet, you won't have any customers or charges to see yet.

**Comment by KimPong** [comment]
@jarvisjohnson do you know if i should be seeing customers in the stripe portal now that people are applying and they have a customer id showing in the portal?

I can't see anyone yet,,

the log in password is vollypower if i haven't sent that already!

**Comment by jarvisjohnson** [comment]
@KimPong You won't see any customers in the dashboard until you have created charges.

The way it works is the customers are created under my stripe account, and then when charges are created through Shyftly under your account for the Stripe customers, they will then show up in your Stripe account.
