### ISSUE TITLE
Applications going through without credit card

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/Strawberry-Fields-2018#8]
@jarvisjohnson heya! I've noticed the applications that have gone through from #27 onwards do not have a Stripe customer ID and have saved without a credit card.

I'm not sure what's changed, but I'm assuming it's something to do with stripe.

At this stage I can just contact those people to request they add a card or they won't be accepted to volunteer etc, but it would be good to get it fixed before we have hundreds to deal with.

I'll try to do some stripe research as soon as I get a chance!

**Comment by KimPong** [comment]
@jarvisjohnson any ideas?

**Comment by jarvisjohnson** [comment]
@KimPong  Whoah thanks for noticing.  

Fortunately everyone's Stripe customer was created, but they didn't get saved for a lot of people for some reason. I've run a script so they all are updated now.  Not sure why some of them have not saved, but I will look into it some more, and we can run the script again when all the applications are closed to make sure everyone is connected to stripe.

**Comment by jarvisjohnson** [comment]
Ok I've updated all of the applications now so they all are connected to stripe.  Will close those seeing as applications are done
