### ISSUE TITLE
Applicant issue: moya_mathias@hotmail.com

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/Strawberry-Fields-2018#9]
@jarvisjohnson 

Can you help me look into this error message supplied by Moya which has prevented her applying?

Perhaps it has to do with her google settings??

I have replied to assure her that we will get it sorted.

![screen shot 2018-08-01 at 6 33 07 pm](https://user-images.githubusercontent.com/29219132/43554009-4452ecda-9635-11e8-96ee-7e275559ca2d.png)

**Comment by jarvisjohnson** [comment]
I really can't say why that is happening for her. The site has an SSL certificate and I secure 

![image](https://user-images.githubusercontent.com/12746936/44310753-8de20300-a3a9-11e8-8b1b-2fd0b9b76dfc.png)

She can just click 'advanced' and proceed from there.
